dart-lightning/lndart.cln

docs.json
docs/index.mdx

docs: add docs conf and fixed link in the docs

---

docs/index.mdx

docs: fixes pending link

---

docs/dev/MAINTAINERS.mdx

ok, this is the last one!
After the review merge it @swaptr

docs: fixed refuse

---

docs/dev/MAINTAINERS.mdx
packages/cln_plugin/example/cln_plugin_example.dart
packages/cln_plugin/lib/src/cln_plugin_base.dart
packages/cln_plugin/lib/src/icln_plugin_base.dart
packages/cln_plugin/lib/src/rpcmethods/abstractrpcmethod.dart
packages/cln_plugin/lib/src/rpcmethods/init/init.dart
packages/cln_plugin/lib/src/rpcmethods/manifest/types/feature.dart
packages/cln_plugin/lib/src/rpcmethods/manifest/types/option.dart
packages/cln_plugin/test/cln_plugin_test.dart

Implementing draft API for plugin development
Working on #3

plugin: draft plugin API

---

packages/cln_plugin/lib/src/json_rpc/error.dart
packages/cln_plugin/lib/src/json_rpc/error.g.dart
packages/cln_plugin/lib/src/json_rpc/request.dart
packages/cln_plugin/lib/src/json_rpc/request.g.dart
packages/cln_plugin/lib/src/json_rpc/response.dart
packages/cln_plugin/lib/src/json_rpc/response.g.dart
packages/cln_plugin/pubspec.yaml

This PR will provide the implementation for the plugin package which was earlier initialized.

plugin: plugin package implementation

---

packages/cln_plugin/lib/src/cln_plugin_base.dart

a small fix with the asynchronous call!

plugin: await the call in the start method

---

packages/cln_plugin/Makefile
packages/cln_plugin/lib/src/json_rpc/error.dart
packages/cln_plugin/lib/src/json_rpc/request.dart
packages/cln_plugin/lib/src/json_rpc/request.g.dart
packages/cln_plugin/lib/src/json_rpc/response.dart
packages/cln_plugin/lib/src/json_rpc/response.g.dart

plugin: fixed the reponse and request format

---

packages/cln_plugin/lib/src/cln_plugin_base.dart
packages/cln_plugin/lib/src/rpc_method/types/option.dart

Fixes https://github.com/dart-lightning/lndart.clightning/issues/29

plugin: adding parsing options

---

.github/workflows/build_packages.yml
Makefile
docker/docker-compose.yaml
docker/sandbox/entrypoint.sh
docker/sandbox/lightning_dir_one/config
melos.yaml
packages/cln_plugin/pubspec.yaml
packages/cln_plugin/test/cln_plugin_integration_test.dart

Fixes https://github.com/dart-lightning/lndart.clightning/issues/28
Just keep sure that we did not introduce regression

ci: integration testing support plugin too

---

packages/cln_plugin/example/cln_plugin_example.dart
packages/cln_plugin/lib/src/cln_plugin_base.dart

This PR allows running a custom code in the init request and taking some information from the configuration.
This is a first step to integrate the rpc wrapper

plugin: implement onInit callback

---

packages/cln_plugin/example/cln_plugin_class_example.dart
packages/cln_plugin/lib/src/cln_plugin_base.dart
packages/cln_plugin/lib/src/json_rpc/request.dart
packages/cln_plugin/lib/src/json_rpc/request.g.dart
packages/cln_plugin/test/cln_jrpc_test.dart

This will fix logging issue.
Fixes #52

plugin: login fix.

---

packages/cln_plugin/lib/src/cln_plugin_base.dart
packages/cln_plugin/lib/src/rpc_method/builtin/get_manifest.dart
packages/cln_plugin/lib/src/rpc_method/builtin/init.dart
packages/cln_plugin/lib/src/rpc_method/rpc_command.dart
packages/cln_plugin/lib/src/rpc_method/types/rpc_type.dart

this will allow rpccommand to be inherited by other types.

plugin: rpccommand refactoring.

---

packages/cln_plugin/README.md
packages/cln_plugin/example/cln_plugin_class_example.dart
packages/cln_plugin/example/cln_plugin_example.dart
packages/cln_plugin/lib/src/cln_plugin_base.dart

Improves readme and adding docs.
fixes #37 #38

plugin: docs and readme.

---

packages/cln_plugin/lib/src/cln_plugin_base.dart
packages/cln_plugin/test/cln_plugin_method_test.dart

this pr will add unit testing to the `cln_plugin` package.
Fixes https://github.com/dart-lightning/lndart.clightning/issues/56
Fixes https://github.com/dart-lightning/lndart.clightning/issues/41

plugin: unit tests.

---

README.md

This PR will fix all README issues, once and for all :)

docs: README fix.

---

.github/workflows/build_common.yml
.github/workflows/build_lnlambda.yml
.github/workflows/testing_rpc.yml
Makefile
docker/Dockerfile.integration_test
docker/docker-compose.yaml
docker/sandbox/lightning_dir_one/config
melos.yaml
packages/cln_common/analysis_options.yaml
packages/lnlambda/.gitignore
packages/lnlambda/CHANGELOG.md
packages/lnlambda/Makefile
packages/lnlambda/README.md
packages/lnlambda/analysis_options.yaml
packages/lnlambda/changelog.json
packages/lnlambda/example/lnlambda_example.dart
packages/lnlambda/lib/lnlambda.dart
packages/lnlambda/lib/src/lnlambda_base.dart
packages/lnlambda/lib/src/model/lnlambda_model.dart
packages/lnlambda/lib/src/model/lnlambda_model.g.dart
packages/lnlambda/pubspec.yaml
packages/lnlambda/test/lnlambda_test.dart

Implementing a client to work with lnlambda https://github.com/clightning4j/lnlambda
cc @KAVAN-DESAI a new client for the cln app with a few lines of code :)
lets see to make happi the CI too now

lnlambda: add new package for lnlambda handling

---

README.md
packages/cln_common/README.md
packages/cln_common/changelog.json
packages/cln_common/example/cln_common_example.dart
packages/cln_common/example/loggin_example.dart
packages/cln_common/pubspec.yaml
packages/cln_plugin/README.md
packages/cln_plugin/pubspec.yaml
packages/lnlambda/README.md
packages/rpc/README.md
packages/rpc/changelog.json
packages/rpc/pubspec.yaml

Fixes https://github.com/dart-lightning/lndart.clightning/issues/63
Fixes  https://github.com/dart-lightning/lndart.cln_grpc/issues/24

docs: completed docs description and changelog configuration

---

packages/cln_plugin/pubspec.yaml
packages/lnlambda/pubspec.yaml
packages/rpc/CHANGELOG.md

rpc: fixed changelog

---

.github/workflows/cln_plugin_release.yml
README.md
melos.yaml
packages/cln_plugin/example/cln_plugin_class_example.dart
packages/cln_plugin/example/cln_plugin_example.dart
packages/cln_plugin/lib/src/cln_plugin_base.dart
packages/cln_plugin/lib/src/icln_plugin_base.dart
packages/cln_plugin/lib/src/rpc_method/builtin/get_manifest.dart
packages/cln_plugin/lib/src/rpc_method/builtin/init.dart
packages/cln_plugin/lib/src/rpc_method/rpc_command.dart
packages/cln_plugin/lib/src/rpc_method/types/rpc_type.dart
packages/cln_plugin/pubspec.yaml
packages/cln_plugin/test/cln_plugin_method_test.dart

cln_plugin: name package name to make happy pub.dev

---

README.md

docs: fix readme by adding badges

---

README.md
docs.json
docs/dev/MAINTAINERS.mdx
docs/index.mdx
packages/cln_common/README.md
packages/cln_common/changelog.json
packages/cln_common/lib/src/client/client.dart
packages/cln_common/lib/src/json_rpc/request.dart
packages/cln_common/pubspec.yaml
packages/cln_plugin/README.md
packages/cln_plugin/changelog.json
packages/lnlambda/changelog.json
packages/rpc/README.md
packages/rpc/changelog.json

This would fix most docs typos.

docs: final docs fixes.

---

docs/index.mdx

docs: fix docs index.mdx

---

README.md
docs/index.mdx

This hook will update `docs/index.mdx` if there were changes in `README.md.
Note: Merge after #78 for a cleaner commit history :)

docs: fix docs and rendering issues with index.mdx

---

packages/rpc/lib/src/clightning_rpc.dart

fix:  fix flutter compatibility force the call `toJSON`

---

packages/rpc/CHANGELOG.md
packages/rpc/changelog.json
packages/rpc/pubspec.yaml

rpc: prepare v0.2.0-beta.2

---

packages/cln_common/.pubignore
packages/cln_plugin/.pubignore
packages/lnlambda/.pubignore
packages/rpc/.pubignore.1

Fixes https://github.com/dart-lightning/lndart.cln/issues/83

packages: add pub ignore

---

docs/dev/MAINTAINERS.mdx

docs: update hacking guide

---

packages/lnlambda/CHANGELOG.md
packages/lnlambda/changelog.json

lnlambda: prepare v0.0.1-beta.2

---

packages/lnlambda/changelog.json
packages/lnlambda/lib/src/lnlambda_base.dart
packages/lnlambda/pubspec.yaml

fix(lnlambda): unwrap the payload from the commando wrapper

---

packages/lnlambda/CHANGELOG.md

add changelog for lnlambda

---

melos.yaml
packages/rpc/lib/src/clightning_rpc.dart
packages/rpc/lib/src/utils/exception/ln_client_error.dart
packages/rpc/lib/src/utils/unix_rpc_client.dart
packages/rpc/test/clightning_rpc_test.dart

bugfix: added error handling.

---

packages/rpc/CHANGELOG.md
packages/rpc/changelog.json
packages/rpc/pubspec.yaml

rpc: prepare release v0.0.2-bata.3

---

packages/rpc/lib/clightning_rpc.dart

fix(rpc): export the exception and make it public

---

packages/rpc/CHANGELOG.md
packages/rpc/changelog.json
packages/rpc/pubspec.yaml

rpc: prepare v0.0.2-beta.4

---

packages/cln_plugin/CHANGELOG.md
packages/cln_plugin/changelog.json
packages/cln_plugin/pubspec.yaml

plugin: prepare v0.0.1-beta.2

---

packages/lnlambda/changelog.json
packages/lnlambda/lib/src/lnlambda_base.dart

fix(lnlambda): fix `XMLHttpRequest` exception

---

packages/lnlambda/CHANGELOG.md
packages/lnlambda/pubspec.yaml

lnlambda: prepare release

---

packages/lnlambda/lib/src/lnlambda_base.dart

fix(lnlambda): fix header

---

packages/cln_common/lib/src/json_rpc/error.dart

fix(plugin): fix the stringify `toJson` method

---

packages/lnlambda/lib/src/lnlambda_base.dart

fix(lnlambda): cleanup cors request headers

---

packages/lnlambda/CHANGELOG.md
packages/lnlambda/changelog.json
packages/lnlambda/pubspec.yaml

docs(lnlambda): prepare beta 5

---

packages/cln_common/lib/src/cln_common_base.dart
packages/cln_common/lib/src/utils/exception.dart
packages/lnlambda/lib/src/lnlambda_base.dart
packages/lnlambda/pubspec.yaml
packages/rpc/lib/clightning_rpc.dart
packages/rpc/lib/src/utils/unix_rpc_client.dart
packages/rpc/pubspec.yaml
packages/rpc/test/clightning_rpc_test.dart

This commit adds the LNClientException class for all the packages by importing it from the rpc package.

fix : adds the LNClientException dependency

---

packages/cln_common/CHANGELOG.md
packages/cln_common/pubspec.yaml
packages/cln_plugin/pubspec.yaml
packages/lnlambda/pubspec.yaml
packages/rpc/pubspec.yaml

Keep the stuff simple here, the `^` should do the trick

dep: fixing how we mange the dependencies
